name: test
on:
  pull_request:
    paths:
      - 'sample/**'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: test
        timeout-minutes: 1
        run: |
          make init test
